export const GET_PREVIEWS = 'GET_PREVIEWS';
export const GET_SINGLE_PREVIEW = 'GET_SINGLE_PREVIEW';

export const GET_RESUME_PDF = 'GET_RESUME_PDF';
export const GET_RESUME_DOCX = 'GET_RESUME_DOCX';
export const RESET_DOWNLOAD_LINKS = 'RESET_DOWNLOAD_LINKS';

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
