export const GET_PREVIEWS = 'GET_PREVIEWS';
export const GET_PREVIEWS_FOR_EACH = 'GET_PREVIEWS_FOR_EACH';
export const GET_SINGLE_PREVIEW = 'GET_SINGLE_PREVIEW';

export const GET_RESUME_PDF = 'GET_RESUME_PDF';
export const GET_RESUME_DOCX = 'GET_RESUME_DOCX';
export const RESET_DOWNLOAD_LINKS = 'RESET_DOWNLOAD_LINKS';
export const GET_USER_RESUMES = 'GET_USER_RESUMES';
export const SAVE_USER_RESUME = 'SAVE_USER_RESUME';
export const RENAME_RESUME = 'RENAME_RESUME';
export const DELETE_RESUME = 'DELETE_RESUME';
export const DELETE_LOCAL_RESUME = 'DELETE_LOCAL_RESUME';

export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const TOKEN_CHECKED = 'TOKEN_CHECKED';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const PUSH_MESSAGE = 'PUSH_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const REMOVE_ALL_MESSAGES = 'REMOVE_ALL_MESSAGES';
